name: EC-KAP1 Verify Files

on:
  push:
    branches:
      - main

jobs:
  ec:
    name: Easycrypt Proof Checking
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v6
    - name: Compile Project
      run: |
        docker run \
          -v .:/home/charlie/project:Z \
          ghcr.io/easycrypt/ec-test-box:release \
          sh -c "opam exec -- make -C project check"
